palette = "catppuccin_latte"

format = """
$username\
$hostname\
$directory\
$aws\
$direnv\
$git_branch\
$git_commit\
$git_status\
$git_state\
$python\
$fill\
$time\
$line_break\
$cmd_duration\
$character"""

scan_timeout = 30
command_timeout = 500
add_newline = false
follow_symlinks = true

[username]
style_user = 'bright-black'
style_root = 'red dimmed'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@$hostname](bright-black) '
disabled = false

[directory]
style = "green"
truncation_length=10
truncate_to_repo=false
truncation_symbol='.../'

[character]
success_symbol = "[»](green)"
error_symbol = "[»](red)"

[git_branch]
format = "[$branch]($style)"
style = "dimmed white"

[git_commit]
commit_hash_length = 6
disabled=false
only_detached=false
style = "dimmed teal"
format='[ $hash]($style) '

[git_status]
style = "dimmed teal"
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)]($style) ($ahead_behind$stashed)]($style)"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕${count}"
up_to_date = "[✔]"
untracked = "?${count}"
stashed = "\\$${count}"
modified = "M${count}"
staged = "+${count}"
renamed = "R${count}"
deleted = "-${count}"
typechanged = ""

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "dimmed teal"

[cmd_duration]
format = "[$duration]($style) "
style = "dimmed yellow"

[python]
format = "[$virtualenv ${version}]($style) "
style = "blue dimmed"
version_format = "${raw}"

[fill]
symbol = ' '
style = ''

[time]
format='[$time]($style)'
style = 'overlay0'
disabled=false
time_format='%T %d-%m'

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
